name: wasg-register-gui
version: 0.0.1
summary: Wireless@SGx Linux Unofficial GUI Interface
description: An unofficial GUI frontend for the wasg-register.py script. A community service project for our fellow Linux using Singaporeans by Custom Automated Systems ® Pte Ltd. https://customautosys.com/wasg-register-gui
base: core18
grade: stable
confinement: strict
icon: icon_cas.png

parts:
  wasg-register-gui:
    plugin: make
    source-type: git
    source: https://github.com/customautosys/wasg-register-gui.git
    build-packages:
      - libwxgtk3.0-gtk3-dev
      - python3
      - python3-pip
    stage-packages:
      - libwxgtk3.0-0v5
      - python3
      - libatk-bridge2.0-0
      - libatspi2.0-0
      - libcairo-gobject2
      - libepoxy0
      - libgtk-3-0
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libwxgtk3.0-gtk3-0v5
      - libxkbcommon0
  pip:
    plugin: python
    python-packages:
      - pycryptodome
      - requests

apps:
  wasg-register-gui:
    command: desktop-launch $SNAP/bin/wasg-register-gui
    extensions:
      - gnome-3-28
    plugs:
      - desktop